config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :books do
    resources :comments
    collection do
      get 'search'
    end
  end
  resources :authors
  devise_for :users
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root 'users#index'
    resources :comments
    resources :categories
    resources :books do
      member do
        post :change_status
      end
    end
    resources :authors do
      member do
        post :change_status
      end
    end
    resources :users do
      member do
        post :change_status
      end
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authors_books
  has_many :categories_books
  has_many :authors, through: :authors_books
  has_many :categories, through: :categories_books
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :desc, presence: true
  validates :agreement, acceptance: { accept: true }

  mount_uploader :image, BookUploader

  def rating
    array = []
    comments.each do |comment|
      array << comment.rating
    end
    (array.inject{ |sum, el| sum + el }.to_f / array.size).round(1)
  end

  def change_status
    active? ? (update_attribute :active, false) : (update_attribute :active, true)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  def index
    @books = Book.all
  end

  def change_status
    @book = Book.find(params[:id])
    @book.change_status
    redirect_back(fallback_location: root_path)
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(active:true).page(params[:page]).per(20)
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  def create
    @user = current_user
    @book = @user.books.new(book_params)
    if @book.save
      params[:book][:categories].each do |category|
        CategoriesBook.create(book: @book, category_id: category.to_i) unless category.blank?
      end
      params[:book][:authors].each do |author|
        AuthorsBook.create(book: @book, author_id: author.to_i) unless author.blank?
      end
      redirect_to root_path, notice: 'Created, but need to approve'
    else
      render 'books/new'
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    search = params[:search]
    @books = Book.where('title LIKE ? OR desc LIKE ?', "%#{search}%", "%#{search}%").page(params[:page]).per(20)
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :image, :desc, :agreement)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/index.html.erb
<div class="span5">
  <table class="table table-striped table-condensed">
    <thead>
    <tr>
      <th>Title</th>
      <th>Date created</th>
      <th>User</th>
      <th>Status</th>
      <th>Comments</th>
    </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
        <% book.active? ? label_type = 'success' : label_type = 'danger' %>
        <% book.active? ? book_status = 'active' : book_status = 'inactive'  %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= book.user.email %></td>
          <td><span class="label label-<%= label_type %>"><%= link_to book_status, change_status_admin_book_path(book), method: :post %><br></span>
          <td><%= link_to 'Show Comments', admin_book_path(book) %></td>
          </td>
        </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/admin/books/show.html.erb
<h2><%= @book.title %> Comments</h2>
<div class="span5">
  <table class="table table-striped table-condensed">
    <thead>
    <tr>
      <th>Body</th>
      <th>Date created</th>
      <th>User</th>
      <th>Rating</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @book.comments.each do |comment| %>
        <tr>
          <td><%= comment.body %></td>
          <td><%= comment.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= comment.user.email %></td>
          <td><%= comment.rating %></td>
          <td><%= link_to 'delete', admin_comment_path(comment), method: :delete %></td>
          </td>
        </tr>
    <% end  %>
    </tbody>
  </table>
</div>