config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :books do
    resources :comments
    collection do
      get 'search'
    end
  end
  resources :authors
  devise_for :users
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root 'users#index'
    resources :comments
    resources :categories
    resources :books do
      member do
        post :change_status
      end
    end
    resources :authors do
      member do
        post :change_status
      end
    end
    resources :users do
      member do
        post :change_status
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :logout_if_inactive

  private

  def logout_if_inactive
    sign_out :user unless user_signed_in? && current_user.active?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
          BOOKS
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <%= render 'books/search_form' %>
      <ul class="nav navbar-nav">
      <li><%= link_to 'Admin Panel', admin_users_path if can? :manage, :all %></li>
      <li><%= link_to 'Add Book', new_book_path if can? :create, Book %></li>
      <li><%= link_to 'Add Author', new_author_path if can? :create, Author %></li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <p class="navbar-text">
              Hello, <%= link_to current_user.email, class: 'navbar-link' %>
            </p>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="dropdown_accaunt"><%= t 'account' %>
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li>1</li>
                  <li class="divider"></li>
                  <li><%= link_to (t 'sign_out'), destroy_user_session_path, method: :delete, id: 'log_out' %></li>
                </ul>
              </li>
            </ul>
        <% else %>
            <ul class="nav navbar-nav">
              <li><%= link_to (t 'sign_up'), new_user_registration_path, id: 'sign_up' %></li>
              <li><%= link_to (t 'sign_in'), new_user_session_path, id: 'log_in' %></li>
            </ul>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application/_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
      <li><%= link_to 'All_books', root_path %></li>
      <% Category.all.each do |category| %>
      <li><%= link_to category.title, category_path(category) %></li>
      <% end %>
  </ul>
</div>

app/views/layouts/application/_sidebar_admin.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li><%= link_to 'Books', admin_books_path %></li>
    <li><%= link_to 'Users', admin_users_path %></li>
    <li><%= link_to 'Categories', admin_categories_path %></li>
    <li><%= link_to 'Authors', admin_authors_path %></li>
  </ul>
</div>